# ------------------------------------------------------------------------------
#  (c) Crown copyright Met Office. All rights reserved.
#  The file LICENCE, distributed with this code, contains details of the terms
#  under which the code may be used.
# ------------------------------------------------------------------------------
# Run Python checks

name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  checks:
    runs-on: "ubuntu-24.04"
    timeout-minutes: 5
    env:
      UV_PYTHON: '3.12.5'
      VENV_PATH: '.venv'

    steps:
      - uses: actions/checkout@v6

      - name: Setup uv
        uses: astral-sh/setup-uv@v7
        with:
          python-version: ${{ env.UV_PYTHON }}
          enable-cache: true

      - name: Cache uv venv
        uses: actions/cache@v4
        with:
          path: ${{ env.VENV_PATH }}
          key: ${{ runner.os }}-${{ hashFiles('uv.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ hashFiles('uv.lock') }}
            ${{ runner.os }}

      - name: Install dependencies
        run: uv sync --locked --all-extras --dev

      - name: Lint Python code
        if: always()
        run: uv run ruff check .

      - name: Format Python code
        if: always()
        run: uv run ruff format --check .

      - name: Run Python tests
        if: always()
        run: uv run pytest tests

      - name: Minimise uv cache
        run: uv cache prune --ci
