# ------------------------------------------------------------------------------
#  (c) Crown copyright Met Office. All rights reserved.
#  The file LICENCE, distributed with this code, contains details of the terms
#  under which the code may be used.
# ------------------------------------------------------------------------------
# Check Contributor License Agreement

name: Legal

on:
  pull_request_target:

jobs:
  cla:
    uses: MetOffice/growss/.github/workflows/cla-check.yaml@main
    with:
      runner: 'ubuntu-24.04'
